# Generated by Django 4.1.7 on 2023-02-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sudentname',
            new_name='studentname',
        ),
    ]
